after: 'curl -s localhost'
packages:
    - name: php
    - name: libapache2-mod-php
    - name: apache2
files:
    - path: /var/www/html/index.php
      source: https://sethrylan.org/sscmt/index.txt
      owner: root
      group: root
      permissions: 0644
      after: 'rm -f /var/www/html/index.html && service apache2 start && service apache2 reload'
