url:         http://sethrylan.org
baseurl:     /
title:       sethrylan.org
port:        4000
safe:        true
lsi:         true
highlighter: rouge
permalink:   date
markdown:    kramdown
exclude: ["readme.md", "README.md", "vendor"]
version: 2.0.1
plugins: [jekyll-feed, jekyll-sitemap]
description: Typing, Fast and Slow
feed:
  path: atom.xml
author:
  name:            Seth Rylan Gainey
  email:           mailto:seth@sethrylan.org
  obfuscatedemail: mailto:seth{at}sethrylan{dot}org
  github:          https://github.com/sethrylan
navigation:
  - text:    Home
    url:     /index.html
