url:         http://sethrylan.org
baseurl:     /
title:       sethrylan.org
port:        4000
safe:        true
lsi:         true
highlighter: rouge
permalink:   date
markdown:    kramdown
googleanalytics:
  account:   UA-33138107-1
author:
  name:      Seth Rylan Gainey
  email:     seth@sethrylan.org
  obfuscatedemail: mailto:seth{at}sethrylan{dot}org
  profiles:
    - label: GitHub
      url:   https://github.com/sethrylan
      text:  Code and Research Papers
    - label: Pinboard
      url:   https://pinboard.in/u:sethrylan
      text:  Bookmarks for Busy People
    - label: StackOverflow
      url:   http://stackoverflow.com/users/1585816/seth-rylan
      text:  Questions and Answers 
navigation:
  - text:    Home
    url:     /index.html
projects:
  - label: An Educated Guess
    url:   /bayesian
    text:  Calibrated Probability Assessment   # Redirect to gh-pages branch of sethrylan.github.com/bayesian repo
  - label: Something Old, Something New
    url:   /2013/12/15/something-old-something-new.html
    text:  Age of Buildings in Charleston, South Carolina
