url:         http://sethrylan.org
baseurl:     /
title:       sethrylan.org
port:        4000
safe:        true
lsi:         true
highlighter: rouge
permalink:   date
markdown:    kramdown
exclude: ["readme.md", "README.md"]
version: 2.0.1
plugins: [jekyll-feed, jekyll-sitemap]
description: Typing, Fast and Slow
feed:
  path: atom.xml
ga_tracking_id:   UA-33138107-1
author:
  name:            Seth Rylan Gainey
  email:           mailto:seth@sethrylan.org
  obfuscatedemail: mailto:seth{at}sethrylan{dot}org
  github:          https://github.com/sethrylan
  stackoverflow:   http://stackoverflow.com/users/1585816/seth-rylan
navigation:
  - text:    Home
    url:     /index.html
projects:
  - title: An Educated Guess
    url:   /bayesian
    text:  Calibrated Probability Assessment   # Redirect to gh-pages branch of sethrylan.github.com/bayesian repo
  - title: Something Old, Something New
    url:   /2013/12/15/something-old-something-new.html
    text:  Age of Buildings in Charleston, South Carolina
