url:         http://sethrylan.org
baseurl:     /
title:       sethrylan.org
port:        4000
safe:        true
lsi:         true
highlighter: rouge
permalink:   date
markdown:    kramdown
exclude: ["readme.md", "README.md", "vendor"]
version: 2.0.1
plugins: [jekyll-feed, jekyll-sitemap]
feed:
  path: atom.xml
